### ISSUE TITLE
varying scale order in info

### ISSUE THREAD

**Issue by d-v-b** [google/tensorstore#10]
relates to https://github.com/google/neuroglancer/issues/237

Occasionally I observe that the order of the `scales` attribute in `info` has an unexpected order, e.g.,  the `s0` scale is sometimes the last element rather than the first. This has only happened twice so far, and the mis-ordering was different both times, which isn't a lot to go on I'm afraid :)

I initialize my collection of tensorstore arrays with this function, which receives a list of `xarray.DataArray`, a list of keys (e.g., s0, s1, etc), and other args. It basically calls `tensorstore.open(spec, **kwargs)` sequentially in a loop, where `spec` is varying. 

the `NicerTensorStore` object is an out-dated workaround to the pickling issue that I don't really need anymore, so ignore that :)

```python
def prepare_tensorstore(pyr: List[xarray.DataArray], level_names: List[str], jpeg_quality: int, output_chunks: Tuple[int], root_container_path: str):
    store_arrays = []
    for p, ln in zip(pyr, level_names):
        res = [float(p.coords[k][1] - p.coords[k][0]) for k in p.dims]
        spec = {'driver': 'neuroglancer_precomputed',
        'kvstore': {'driver': 'file', 
                    'path': str(Path(root_container_path).parent)},
        'path': root_container_path.parts[-1],
        'scale_metadata': {'size': p.shape,
        'resolution': res,
        'encoding': 'jpeg',
        'jpeg_quality': jpeg_quality,
        'chunk_size': output_chunks,
        'key': ln,
        'voxel_offset': (0, 0, 0)},
        'multiscale_metadata': {'data_type': p.dtype.name,
        'num_channels': 1,
        'type': 'image'}}
        try: 
            ts.open(spec=spec, open=True).result()
        except ValueError:
            try:
                ts.open(spec=spec, create=True).result()
            except ValueError:
                ts.open(spec=spec, create=True, delete_existing=True).result()

        nicer_array = NicerTensorStore(spec=spec, open_kwargs={'write': True})
        store_arrays.append(nicer_array)
    return store_arrays
```

**Comment by jbms** [comment]
I took a look at the code in tensorstore responsible for creating a new scale.  While it is certainly possible there is bug, it certainly looks like new scales should be added at the end.  Is it possible that pyr/level_names may be in the wrong order to start with?

**Comment by d-v-b** [comment]
I don't think order of the pyramids / level names ever changes, but a more likely possibility is that I wasn't completely deleting everything before re-generating the store, so `s1` existed before `s0` was created. 

I'll close this, and if I get around to formally testing this / learning more about the issue I can reopen.
