### ISSUE TITLE
Custom CA cert file name

### ISSUE THREAD

**Issue by stuarteberg** [google/tensorstore#11]
When I try to use `tensorstore` from the Janelia cluster, I encounter the following error:

```
ValueError: Error opening "neuroglancer_precomputed" driver:
Error reading "gs://neuroglancer-janelia-flyem-hemibrain/v1.1/segmentation/info":
CURL error[77] Problem with the SSL CA cert (path? access rights?):
error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```

Indeed, the file `/etc/ssl/certs/ca-certificates.crt` does not exist on our cluster nodes.  Instead, I see `/etc/ssl/certs/ca-bundle.crt`, but unfortunately I don't have the necessary permissions to add a symlink.

Is it possible for the user to provide a custom file path for the cert file?  Apparently the `curl` command line tool allows it to be configured at runtime, but I guess that configuration isn't built into `libcurl` itself.

**Comment by jbms** [comment]
libcurl doesn't support environment variables for configuration natively like the command-line tool does, but I'll add some to TensorStore and hopefully push out an update tomorrow.

**Comment by jbms** [comment]
Refer to the documentation here: https://google.github.io/tensorstore/environment.html#tls-ca-certificates

**Comment by stuarteberg** [comment]
Just tested `0.1.6` with the new environment variable.  It works!  Thanks!
