### ISSUE TITLE
Fail to create files on windows network drive using zarr driver.

### ISSUE THREAD

**Issue by ztzhu1** [google/tensorstore#123]
Hi, guys! I want to create and modify datasets remotely via windows 10 network drive. Suppose my local host IP is 192.168.10.9 and I want to create a dataset on a remote host whose IP is 192.168.10.11 by using tensorstore.open(). Here is the code,

```python
import tensorstore as ts

spec = {
    "driver": "zarr",
    "kvstore": {
        "driver": "file",
        "path": r"\\192.168.10.11\ztzhu\test.zarr",
    },
    "create": True,
    "delete_existing": True,
}
dataset = ts.open(spec, dtype=ts.float32, shape=(10,)).result()
```
But it raises `ValueError` without any extra information. It seems not to be caused by permission because `tensorstore` does create the folder `test.zarr` and the file `.zarray.__lock`. Then it's stuck. Besides, I can create the dataset by using `zarr` directly,
```python
import zarr

zarr.open(r"\\192.168.10.11\ztzhu\test.zarr", mode='w', dtype=np.float32, shape=(10,))
```
The code above works as expected.

I have googled this and read the document but I didn't find a satisfying answer. My tensorstore version is `0.1.45`. Could you guys kindly help me? Thanks a lot!

**Comment by laramiel** [comment]
Our file validation may not handle windows network paths properly.  Does it work if you use the `Map Network Drive` functionality and remap "\\192.168.10.11\zthzu" to something like X: ?

**Comment by ztzhu1** [comment]
> Our file validation may not handle windows network paths properly. Does it work if you use the `Map Network Drive` functionality and remap "\192.168.10.11\zthzu" to something like X: ?

I tried, it still doesn't work :)

**Comment by tindiz** [comment]
I believe I have a similar issue. Have you managed to find a workaround and fix this?

**Comment by ztzhu1** [comment]
> I believe I have a similar issue. Have you managed to find a workaround and fix this?

Sadly, no. I have to create and write files locally and move them to a remote host using other packages manually.
