### ISSUE TITLE
No tensorstore conda package for `osx-arm64`

### ISSUE THREAD

**Issue by pierreglaser** [google/tensorstore#128]
Title says it all - reproducer below:

```
~❯_ mamba search 'tensorstore[subdir=osx-arm64]'
Loading channels: done
No match found for: tensorstore[subdir=osx-arm64]. Search: *tensorstore*[subdir=osx-arm64]
```
versions:

```
mamba 1.5.1
conda 23.7.4
```

Any plans to add a tensorstore conda package for this platform? Thanks!

**Comment by jbms** [comment]
We do have a macos arm package on PyPI.  We aren't responsible for the conda package though.

**Comment by stuarteberg** [comment]
@pierreglaser

Indeed, there are no `osx-64` or `osx-arm64` packages on the conda-forge channel:
https://anaconda.org/conda-forge/tensorstore/files

To start the discussion, you could open an issue on the following repo:
https://github.com/conda-forge/tensorstore-feedstock

Or, perhaps even better, you could open a PR in that repo and edit the following line so it stops skipping `osx`:
https://github.com/conda-forge/tensorstore-feedstock/blob/main/recipe/meta.yaml#L18

Presumably, the build will fail, and you'll have inspect the build output and try to figure out what needs to change.  (Or ask for help.)

---

### Background

Looks like they created the initial "feedstock" for tensorstore as soon as the linux build worked, with the intention of iterating further on the osx build later.  Here are two comments from the original thread:

- https://github.com/conda-forge/staged-recipes/pull/17848#issuecomment-1773251777
- https://github.com/conda-forge/staged-recipes/pull/17848#pullrequestreview-1691278564

**Comment by pierreglaser** [comment]
> We aren't responsible for the conda package though.

Did not know that!

Thanks @stuarteberg for the informative suggestions and references. Will try and naively remove the skipping of `osx` platforms `meta.yml`.

**Comment by psobolewskiPhD** [comment]
FYI, I think you can close this as of https://github.com/conda-forge/tensorstore-feedstock/pull/22
On my M1, arm64 conda env:
```
╰─ mamba repoquery search tensorstore                                (nap-3d) ─╯

Executing the query tensorstore

conda-forge/osx-arm64                                9.6MB @  15.3MB/s  0.6s
conda-forge/noarch                                  14.6MB @  13.0MB/s  1.1s


 Name        Version Build                        Channel     Subdir   
────────────────────────────────────────────────────────────────────────
 tensorstore 0.1.57  py310h6e3bce1_0 (+ 3 builds) conda-forge osx-arm64
 tensorstore 0.1.56  py310h20bb696_0 (+ 3 builds) conda-forge osx-arm64
 tensorstore 0.1.55  py310h20bb696_0 (+ 3 builds) conda-forge osx-arm64
 tensorstore 0.1.54  py310h20bb696_4 (+ 7 builds) conda-forge osx-arm64
```

**Comment by pierreglaser** [comment]
Great!
