### ISSUE TITLE
Please create a pre-built PyPI wheel for linux arm64 

### ISSUE THREAD

**Issue by andrewstein** [google/tensorstore#136]
The title says it all... 

On [https://pypi.org/project/tensorstore/#files](https://pypi.org/project/tensorstore/#files) there are pre-builts for `macosx...arm64` on the one hand, and for `manylinux...x86_64` on the other, but none for `manylinux...aarch64`

**Comment by jbms** [comment]
See also https://github.com/google/tensorstore/issues/77

We would like to have them, but it is challenging because we currently build on Github-hosted runners which do not include a linux arm64 runner, and building under emulation via qemu is possible but so slow that we decided not to enable that.  Cross-compiling would be fast but I could not find a suitable manylinux cross-compilation container with a sufficiently recent GCC version.

Maybe it could be done now by running a linux docker image on the Github-hosted macos arm64 runner.

**Comment by sjperkins** [comment]
If gcc 12.2 is sufficiently recent for cross-compilation, it may be worth considering changing the CIBW manylinux containers from `manylinux2014` to `manylinux_2_28`. Additionally, `Centos 7`, on which `manylinux2014` is based, will reach [EOL](https://cloud.google.com/compute/docs/eol/centos-eol-guidance) on [June 30th 2024](https://github.com/pypa/manylinux).

**Comment by jbms** [comment]
Yes we were planning to move to manylinux_2_28 anyway for C++20 support.  But is there a manylinux_2_28 cross-compilation image with gcc 12?

**Comment by sjperkins** [comment]
> Yes we were planning to move to manylinux_2_28 anyway for C++20 support. But is there a manylinux_2_28 cross-compilation image with gcc 12?

I'm not sure, but it looks like

**Comment by sjperkins** [comment]
> Yes we were planning to move to manylinux_2_28 anyway for C++20 support. But is there a manylinux_2_28 cross-compilation image with gcc 12?

It looks like cross-compiling aarch64 is still an open issue:

- https://github.com/pypa/cibuildwheel/issues/598

**Comment by glenn-jocher** [comment]
We'd like to see this too for https://github.com/ultralytics/ultralytics

**Comment by lakshanthad** [comment]
According to our CIs running on Raspberry Pi 5, it takes around 40min+ to build `tensorstore`. So it would be nice to have prebuilt aarch64 binaries.
![image](https://github.com/google/tensorstore/assets/20147381/3017f16d-916e-43e3-b517-e1b4dec768d5)

https://github.com/ultralytics/ultralytics/actions/runs/9227944458/job/25390932025

**Comment by stuarteberg** [comment]
FWIW, if you use conda, then the conda-forge has `tensorstore` packages for `linux_aarch64`.

https://anaconda.org/conda-forge/tensorstore/files

(I understand that may not help if you are not already using conda and don't want to switch.)
