### ISSUE TITLE
S3 kvstore driver not being recognized

### ISSUE THREAD

**Issue by conochur** [google/tensorstore#139]
Hello! I'm trying to create a precomputed tensorstore object directly in an S3 bucket, and am following the format prescription: 
<img width="452" alt="image" src="https://github.com/google/tensorstore/assets/71669181/f1bf841c-af2a-4798-8495-392ecf2092ce">

However, I'm getting a value error indicating that "s3" isn't a registered key. I confirmed that the other kvstore types are functioning. Thanks!

<img width="546" alt="image" src="https://github.com/google/tensorstore/assets/71669181/1f7d2c2c-e920-461c-98f9-e09c3e5f0a09">

**Comment by jbms** [comment]
Which version of tensorstore are you using?

**Comment by conochur** [comment]
> Which version of tensorstore are you using?

0.1.45

**Comment by conochur** [comment]
> Which version of tensorstore are you using?

I just checked the version history, and I'm clearly behind.
