### ISSUE TITLE
Failing to build tensorestore as a cmake project

### ISSUE THREAD

**Issue by georgeza-dev** [google/tensorstore#151]
Hello,
I am trying to build and link tensorestore library with my c++ code.

I am using cmake approach and follow all the official instructions from here _https://google.github.io/tensorstore_  .
Trying to compile and build cmake project, Unfortunately, I am getting the error below , related to protobufs :

[ 50%] Generating src/google/protobuf/wkt/google/protobuf/any.pb.h, src/google/protobuf/wkt/google/protobuf/api.pb.h, src/google/protobuf/wkt/google/protobuf/duration.pb.h, src/google/protobuf/wkt/google/protobuf/empty.pb.h, src/google/protobuf/wkt/google/protobuf/field_mask.pb.h, src/google/protobuf/wkt/google/protobuf/source_context.pb.h, src/google/protobuf/wkt/google/protobuf/struct.pb.h, src/google/protobuf/wkt/google/protobuf/timestamp.pb.h, src/google/protobuf/wkt/google/protobuf/type.pb.h, src/google/protobuf/wkt/google/protobuf/wrappers.pb.h, src/google/protobuf/wkt/google/protobuf/any.pb.cc, src/google/protobuf/wkt/google/protobuf/api.pb.cc, src/google/protobuf/wkt/google/protobuf/duration.pb.cc, src/google/protobuf/wkt/google/protobuf/empty.pb.cc, src/google/protobuf/wkt/google/protobuf/field_mask.pb.cc, src/google/protobuf/wkt/google/protobuf/source_context.pb.cc, src/google/protobuf/wkt/google/protobuf/struct.pb.cc, src/google/protobuf/wkt/google/protobuf/timestamp.pb.cc, src/google/protobuf/wkt/google/protobuf/type.pb.cc, src/google/protobuf/wkt/google/protobuf/wrappers.pb.cc
**../build/_deps/protobuf-build/src/google/protobuf/wkt/: No such file or directory**
make[2]: *** [deps/protobuf-build/CMakeFiles/genrule__protobuf_src_google_protobuf_gen_wkt_cc_sources.dir/build.make:102: _deps/protobuf-build/src/google/protobuf/wkt/google/protobuf/any.pb.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:59507: _deps/protobuf-build/CMakeFiles/genrule__protobuf_src_google_protobuf_gen_wkt_cc_sources.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Platform:  Ubuntu 20.04.6 LTS (Focal Fossa)

Any ideas would be very much appreciated,
Best regards,

George

**Comment by laramiel** [comment]
Our CI builds tensorstore using CMake on every change, but environments differ.
Could you provide the exact commands you are using?

**Comment by georgeza-dev** [comment]
Hello, thanks for your response.
I am trying to build everything using "**cmake ..** " from ./build directory and then "**make**"  

At the end of the day, I will use it to read/write file based and cloud based zarr directories . 
But I am lacking the way to build only the zarr driver, so tried to build everything.

Thanks in advance for your help.
George

**Comment by laramiel** [comment]
Try using the Ninja generator for cmake.

**Comment by georgeza-dev** [comment]
Thanks for your answer!! I will give a try.
Best,
George
