### ISSUE TITLE
Question: does tensorstore support array with multiple dynamic dimensions?

### ISSUE THREAD

**Issue by yangzq50** [google/tensorstore#158]
I have noticed that in the tutorial the "dataset" is initialized with fixed shape. For example, 'dimensions': [1000, 20000].
Does tensorstore support data type like ` std::vector<std::vector<std::array<float,128>>> ` in C++?

**Comment by jbms** [comment]
That is often called a ragged array and unfortunately tensorstore does not support it.

**Comment by yangzq50** [comment]
Thanks.
