### ISSUE TITLE
anonymous S3

### ISSUE THREAD

**Issue by joshmoore** [google/tensorstore#169]
I'm looking for the equivalent of:

```
aws s3 --no-sign-request --endpoint-url=https://uk1s3.embassy.ebi.ac.uk ls s3://idr
```

for accessing public Zarr files. In one of the open S3 issues, I saw a mention of "empty credentials" enabling anonymous access but have not been able to make that work. (Neither `None` or `""` seem to be permitted in the driver)

## Config

```
        'driver': 'zarr',
        'kvstore': {
            'driver': 's3',
            'endpoint': 'https://uk1s3.embassy.ebi.ac.uk',
            'bucket': 'idr',
            'path': 'zarr/v0.4/idr0062A/6001240.zarr/0',
            'aws_credentials': '',
        },
```

## Error:
```
ValueError: Error parsing object member "kvstore": Error parsing object member "aws_credentials": Invalid reference to "aws_credentials" resource: "" [source locations='tensorstore/context.cc:794\ntensorstore/internal/json_binding/json_binding.h:861\ntensorstore/internal/json_binding/json_binding.h:826\ntensorstore/kvstore/spec.cc:115\ntensorstore/internal/json_binding/json_binding.h:826\ntensorstore/internal/json_binding/json_binding.h:861\ntensorstore/internal/json_binding/json_binding.h:826']
```

**Comment by jbms** [comment]
This works for me:

```python
store = ts.open({
       'driver': 'zarr',
        'kvstore': {
            'driver': 's3',
            'endpoint': 'https://uk1s3.embassy.ebi.ac.uk',
            'bucket': 'idr',
            'path': 'zarr/v0.4/idr0062A/6001240.zarr/0',
            'aws_region': 'us-east-1',
        },
        }).result()
```

The fact that the `aws_region` needs to be specified in this case is unfortunate --- we may be able to fix that.  Tensorstore attempts to determine the aws_region automatically via a HEAD request to `/<bucket>` and expects to get an `x-amz-bucket-region` response header.  Your endpoint does not provide that header, though, so tensorstore currently indicates "bucket not found" if aws_region isn't specified.  The aws region isn't needed for anonymous requests anyway, though, so we could skip determining it in that case.  However, I'm not sure if there would be a way to automatically determine the correct aws_region for your endpoint when doing authenticated requests.

**Comment by laramiel** [comment]
We should skip the aws_region request when endpoint is set and credentials are anonymous, I think.

**Comment by joshmoore** [comment]
Hmmm.... with @jbms' suggestion I'm getting:

```
ValueError: PERMISSION_DENIED: Error opening "zarr" driver: Error reading "zarr/v0.4/idr0062A/6001240.zarr/0/.zarray": HTTP response code: 403 with body: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><RequestId>tx000000000000002067218-0066740596-23b77beb-default</RequestId><HostId>23b77beb-default-default</HostId></Error> [tensorstore_spec='{\"context\":{\"aws_credentials\":{\"filename\":\"\",\"metadata_endpoint\":\"\",\"profile\":\"\"},\"cache_pool\":{},\"data_copy_concurrency\":{},\"s3_request_concurrency\":{},\"s3_request_retries\":{}},\"driver\":\"zarr\",\"kvstore\":{\"aws_region\":\"us-east-1\",\"bucket\":\"idr\",\"driver\":\"s3\",\"endpoint\":\"https://uk1s3.embassy.ebi.ac.uk\",\"path\":\"zarr/v0.4/idr0062A/6001240.zarr/0/\"}}'] [source locations='tensorstore/kvstore/s3/s3_key_value_store.cc:537\ntensorstore/internal/cache/kvs_backed_cache.h:208\ntensorstore/driver/driver.cc:112']
```

including when I move my `.aws` directory out of the way. ~How do I signal that credentials are anonymous?~

Strike that: If I unset `AWS_` environment variables then I get farther. :+1:

It would be nice if I could force ignoring of all aws-isms for a custom endpoint _a la_ the weirdly named `--no-sign-request`

----

Sidenote: this gets printed but I assume it's harmless (though perhaps there's a flag to say, "stay on https"?)

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1718879743.571637 2801329 s3_resource.cc:108] Using default AdmissionQueue with limit 32
W0000 00:00:1718879743.777802 2801336 curl_transport.cc:452] Error [28]=Timeout was reached in curl operation
Failed to connect to 169.254.169.254 port 80 after 205 ms: Timeout was reached
```

**Comment by laramiel** [comment]
Ok, try this in the next release:

```
store = ts.open({
       'driver': 'zarr',
        'kvstore': {
            'driver': 's3',
            'endpoint': 'https://uk1s3.embassy.ebi.ac.uk',
            'bucket': 'idr',
            'path': 'zarr/v0.4/idr0062A/6001240.zarr/0',
            'aws_credentials': { 'anonymous': True, },
        },
}).result()
```

**Comment by laramiel** [comment]
I also committed https://github.com/google/tensorstore/commit/fda853995bdd020a9a2608ac2fb8a1156aa990a5 to reduced the log spam you see there.
