### ISSUE TITLE
Does zarr_sharding_indexed exist?

### ISSUE THREAD

**Issue by dlwh** [google/tensorstore#180]
I see it in the docs, but i can't create it and there doesn't seem any code besides some basic struct definitions (though I didn't attempt to understand the code base that much!)

If not, consider me interested in the feature!

**Comment by jbms** [comment]
Sorry, we need to fix the documentation, the correct name is `zarr3_sharding_indexed`.

This is a kvstore driver which can be used to access an individual zarr v3 sharding_indexed shard.  It is used internally by the zarr v3 driver --- only in special circumstances would you use it directly.
