### ISSUE TITLE
Incorrect writes using int array indexing, affected by chunk layout

### ISSUE THREAD

**Issue by BenTenmann** [google/tensorstore#181]
Hey,
We have been playing with Google TensorStore and have noticed some strange behaviour. When we create a store of rank >= 3, we have found that writing to the store using an integer array index will produce wrong results under certain chunk layouts. For example:

```python
import numpy as np  # version==1.26.4 (also tried 1.23.4)
import tensorstore as ts  # version==0.1.63 (also tried 0.1.54)

x = np.random.randn(10, 21, 5313).astype(np.float32)
store = ts.open(
    {
        "driver": "zarr3",
        "kvstore": {
            "driver": "file",
            "path": "my-store",
        },
        "metadata": {
            "data_type": "float32",
            "shape": [10, 21, 5313],
            "chunk_grid": {
                "name": "regular",
                "configuration": {
                    "chunk_shape": [10, 21, 500],
                }
            },
        },
        "create": True,
        "delete_existing": True,
    }
).result()
store[[0, 1, 2]].write(x[[0, 1, 2]]).result()
assert np.allclose(x[[0, 1, 2]], store[[0, 1, 2]].read().result())
```

the above will fail the assert, because the elements in `x[[0, 1, 2]]` have only partially been written to the store. This problem does not happen when we use `store[:3].write(x[[0, 1, 2]]).result()`. Also, this issue goes away if we set `chunk_shape=[10, 21, 146]` (but reappears for `[10, 21, 147]`). This happens for `n5`, `zarr` and `zarr3` drivers.
We also tried different chunk layouts and tensor shapes, and the problem seems reproducible. But the pattern in shape - chunking relationship is unclear. For rank == 2 this does not seem to happen. Finally, we also tried using `zarr` directly and this does not seem to be an issue there.
We cannot seem to find anything related to this in the docs. Any ideas what the issue here may be?

**Comment by jbms** [comment]
Thanks for this bug report, we'll take a look right away.
