### ISSUE TITLE
Falied to acquire lock on file

### ISSUE THREAD

**Issue by huohuoxi** [google/tensorstore#183]
It is from
https://github.com/google/orbax/discussions/523#discussion-5680922
I have the same problem with this man.
He says,
Hi, I am having some trouble saving a checkpoint. My code is very simple:
```python
PyTreeCheckpointer().save(dir_ / 'actor_params', controller._actor_params)
```
and works fine on my local machine. However, when running on an HPC cluster, I get the following error:
```
ValueError: FAILED_PRECONDITION: Error writing local file "/home/oeberhard/laurel/dat/runs/test/working_directories/1/actor_params.orbax-checkpoint-tmp-1695894959581296/_sharding": Failed to acquire lock on file: /home/oeberhard/laurel/dat/runs/test/working_directories/1/actor_params.orbax-checkpoint-tmp-1695894959581296/_sharding.__lock [OS error: Function not implemented] [source locations='tensorstore/kvstore/file/file_key_value_store.cc:676\ntensorstore/kvstore/kvstore.cc:268']
```

There are no access problems i.e. checkpointing with `flax.training.checkpoints` works perfectly. Is there maybe a way to disable the locking? Thanks!

**Comment by laramiel** [comment]
I added a fallback to ::flock locking in https://github.com/google/tensorstore/commit/5847d9a881513e72e3c4038787fb4df30de08439

Please try it out and indicate whether it works on your network filesystem, as I don't have an equivalent system to test it on.
