### ISSUE TITLE
Parallel write handling in Zarr

### ISSUE THREAD

**Issue by asparsa** [google/tensorstore#185]
I'm trying to get the best writing time from the zarr3 driver. I ran the mentioned code in https://github.com/google/tensorstore/issues/172#issuecomment-2251384523 with different numbers of limits and different system configurations. Shockingly, it will stop improvement at 16, the number of cores in one NUMA. I tried the mentioned approaches to overcome this issue, but none worked. I wanted to scale my writing to more than one node and ask how this can be handled.

**Comment by laramiel** [comment]
.. I'm going to close this. Please move your comment back to the other issue.
