### ISSUE TITLE
Windows: NotImplementedError: CopyRange not supported #1048

### ISSUE THREAD

**Issue by cool-RR** [google/tensorstore#188]
This issue was moved from https://github.com/google/orbax/issues/1048 .

See this code sample:

```python
import pathlib

import orbax.checkpoint

orbax_checkpointer = orbax.checkpoint.PyTreeCheckpointer()
tree = {'key': 7}
path = pathlib.Path(__file__).parent / 'foo'
orbax_checkpointer.save(path, tree)
```

When I run it on Linux, it works fine. When I run it on Windows 10, I get [this traceback](https://gist.github.com/cool-RR/f51c95b1dba9c26be45725cf7e767467) with the exception: `builtins.NotImplementedError: CopyRange not supported`.

The versions I use:

```
orbax-checkpoint==0.5.23
tensorstore==0.1.64
```

**Comment by laramiel** [comment]
I looked into this for a minute. orbax is using ocdbt, which has a specialization to copy between ocdbt datasets.
The typeid check appears to be failing, so I'll have to debug that.

https://github.com/google/tensorstore/blob/afcd7e756e531d616f1e034d195a48c8111e7cb0/tensorstore/kvstore/ocdbt/driver.cc#L339

**Comment by jbms** [comment]
I suspect the issue is related to path normalization.

**Comment by laramiel** [comment]
I verified that is indeed the case.  There is a / directory separator in one place vs a \ in the other.

**Comment by cool-RR** [comment]
Thank you @laramiel . Since pathlib appears to do that on Windows, shouldn't tensorstore detect pathlib paths on Windows and replace the slash?
