### ISSUE TITLE
Writing Neuroglancer Precomputed data with png compression not working correctly

### ISSUE THREAD

**Issue by LarsKoeppel** [google/tensorstore#196]
Hi,

i generated 2 versions of  a dataset with tensorstore. And a 3erd version of the same data with cloud-volume.

The first version uses jpg compression and can be opened normaly:
[jpg version](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B28799.7265625%2C32726.248046875%2C0.5%5D%2C%22crossSectionScale%22:1.6487212707001286%2C%22projectionScale%22:65536%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://data.ariadne.ai/public/01c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c10%22%2C%22tab%22:%22source%22%2C%22name%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c10%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c10%22%7D%2C%22layout%22:%22xy%22%7D)

The second version uses png compression and the image is not fully loaded(border chunks missing):
[png version](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B28846.67578125%2C32702.560546875%2C0.5%5D%2C%22crossSectionScale%22:1.6487212707001309%2C%22projectionOrientation%22:%5B0.0060514663346111774%2C-0.02095727063715458%2C0.002920560073107481%2C0.9997577667236328%5D%2C%22projectionScale%22:65536%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://data.ariadne.ai/public/01c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c09%22%2C%22tab%22:%22source%22%2C%22name%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c09%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c09%22%7D%2C%22layout%22:%22xy%22%7D)

The 3rd version was created using cloud-volume(loads normaly):
[cloud-volume](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B29223.8515625%2C32973.578125%2C0.5%5D%2C%22crossSectionScale%22:0.36787944117144245%2C%22projectionScale%22:65536%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://data.ariadne.ai/public/01c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c11%22%2C%22tab%22:%22source%22%2C%22name%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c11%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%2201c6255ebef92cd11226dae61eeba3f362365347a6912f3dc4ace023757f9c11%22%7D%2C%22layout%22:%224panel%22%7D)

Neuroglancer is not able to show the chunks that overlap the border of the image from the png version made with tensorstore. 
I verified that all chunks are loaded and that the naming of the cunks is identical. I also check this in the Firefox and Edge browser - same result.

I used this config for tensorstore to create this dataset. Did i miss something in the config?
```
tensorstore::Open({{"driver", "neuroglancer_precomputed"},
                                       {"kvstore", {
                                            {"driver", "file"},
                                            {"path", <path>}
                                        }},
                                       {"multiscale_metadata", {
                                            {"data_type", "uint8}, 
                                            {"num_channels", 1},
                                            {"type", "image"},
                                        }},
                                       {"scale_metadata", {
                                            {"resolution", {resolution[0], resolution[1], resolution[2]}},
                                            {"encoding", "png"},
                                            {"png_level", 6},
                                            {"chunk_size", {chunkSize[0], chunkSize[1], chunkSize[2]}},
                                            {"size", {sizeX, sizeY, sizeZ}},
                                        }},
                                       {"scale_index", index},
                                      },
                                      context,
                                      tensorstore::OpenMode::create,
                                      tensorstore::RecheckCached{false},
                                      tensorstore::ReadWriteMode::write).value();
```

I used this code to generate the cloud volume version. So the data is stored in the chunks but not in a format that neuroglancer can read.
```
>>> from cloudvolume import CloudVolume
>>> import tensorstore as ts
>>> dataset = ts.open(
...             {
...                 "driver": "neuroglancer_precomputed",
...                 "kvstore": {
...                     "driver": "file",
...                     "path": <path>,
...                 },
...             }
...         ).result()
>>> data = dataset[:,:,0].read().result()
>>> volume_path = 'file://<output_path>'
>>> info = CloudVolume.create_new_info(
...     num_channels=1,                    # number of channels
...     layer_type='image',                 # 'image' for image data
...     data_type='uint8',                  # data type of your NumPy array
...     encoding='png',                     # use PNG compression
...     resolution=[1, 1, 1],              # in nanometers
...     voxel_offset=[0, 0, 0],             # where the data starts
...     chunk_size=[1024, 1024, 1],             # size of each chunk in voxels
...     volume_size=data.shape,           # volume size in voxels
... )
>>> vol = CloudVolume(volume_path, info=info)
>>> vol.commit_info()  # write the metadata to disk
>>> vol[:,:,0] = data
```

I am happy to help with more information.

**Comment by LarsKoeppel** [comment]
Hello everyone,

I was wondering if there have been any updates on this issue. If there's anything I can do to assist or test, please let me know.

**Comment by laramiel** [comment]
Sorry, no updates. This is on the list, but we haven't had time to prioritize it yet. Hopefully soon.
