### ISSUE TITLE
Zarr v2 raw compressing encoding not accepted by tensorstore

### ISSUE THREAD

**Issue by dchen116** [google/tensorstore#199]
The Zarr v2 specification states the the following about the filters field:

> filters
> A list of JSON objects providing codec configurations, or null if no filters are to be applied. Each codec configuration object MUST contain a "id" key identifying the codec to be used.

n5-zarr encodes "raw compression" as [] rather than null. Tensorstore only accepts null when there are no filters.

**Comment by mkitti** [comment]
It is not clear to me that an empty list, `[]` is disallowed by the Zarr v2 specification.

**Comment by jbms** [comment]
Yes, I believe an empty list is permitted by the zarr v2 spec --- will fix.
