### ISSUE TITLE
Shared Cache for TileServer Proxy with TensorStore

### ISSUE THREAD

**Issue by unidesigner** [google/tensorstore#208]
I'm implementing a tile server backed by tensorstore using [FastAPI](https://fastapi.tiangolo.com/) with [multiple workers](https://fastapi.tiangolo.com/deployment/server-workers/?h=workers). I'd like to use a single common memory cache across the workers and I figured that this may be possible with the Tensorstore [Context Framework](https://google.github.io/tensorstore/context.html#context). 
However, I'm unclear on how to configure such a shared context when opening a dataset. Could you provide any guidance or example code to help? Thank you!

**Comment by jbms** [comment]
There is no way to share the cache across processes, unfortunately.

**Comment by unidesigner** [comment]
Also not with [tmpfs](https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html) ?

**Comment by jbms** [comment]
Certainly there are ways in principle to share a cache across processes, but the cache in tensorstore does not support that.  An alternative would be to use a single-process server, but I don't know if the GIL overhead will be too great.  TensorStore does not yet support nogil Python, but in the future it will, and that will presumably allow for improved multi-threaded server performance.

**Comment by unidesigner** [comment]
I'll look into using a single-process server, and perform benchmarks for different request situations, or deploy single-process servers for different scale levels with background prefetching. It'd be great to be able to also compare performance with nogil Python later.
