### ISSUE TITLE
Writing RGB neuroglancer image with png compression

### ISSUE THREAD

**Issue by LarsKoeppel** [google/tensorstore#209]
Hi,

I'm trying to write an RGB image using TensorStore with PNG compression, but I'm encountering some issues. The resulting image looks strange—similar to subpixels on a display. I've attached images showing the problem (split into individual channels for clarity):

- Red Channel
![Image](https://github.com/user-attachments/assets/43fb7c38-6970-46bc-803c-3377201e62be)

- Green Channel
![Image](https://github.com/user-attachments/assets/2c57b944-e45a-44d3-99c8-b40fe22d9c0a)

- Blue Channel
![Image](https://github.com/user-attachments/assets/1270c2cb-1542-4b6f-8f01-b706e6ebbd90)

For reference, here's how the image is supposed to look:
![Image](https://github.com/user-attachments/assets/6e8b4c2c-5781-4515-9e2f-e92b673eb301)

Here's the code snippet I'm using:
```
tensorstore::Open({{"driver", "neuroglancer_precomputed"},
     {"kvstore", {
          {"driver", "file"},
          {"path", <path>}
      }},
     {"multiscale_metadata", {
          {"data_type", "uint8"},   
          {"num_channels", 3},
          {"type", "image"},
      }},
     {"scale_metadata", {
          {"resolution", {resolution[0], resolution[1], resolution[2]}},
          {"encoding", "png"},
          {"png_level", 6},
          {"chunk_size", {1024, 1024, 1}},
          {"size", {sizeX, sizeY, 1}},
      }},
     {"scale_index", 0},
    },
    context,
    tensorstore::OpenMode::create,
    tensorstore::RecheckCached{false},
    tensorstore::ReadWriteMode::write).value();
```

When I use the same code with a single-channel image, everything works fine. 

Am I doing something wrong? 
Any help or guidance would be greatly appreciated!

**Comment by jbms** [comment]
This is actually a Neuroglancer bug with multi-channel png images, will be pushing out a fix soon.
