### ISSUE TITLE
force write zeros

### ISSUE THREAD

**Issue by fcollman** [google/tensorstore#24]
I am trying to write an array of stimulus for visualization purposes, and so the behavior of skipping writing chunks with all zeros is not appropriate for this use case. I couldn't find an option to override this default behavior... am I missing it?

**Comment by jbms** [comment]
Currently there isn't such an option.  If a chunk is entirely equal to the fill value, it will be "written" by deleting the file.  I suppose there could be an option to override that, but what is the benefit?  Reading back from tensorstore will return the correct result.

Is the issue that there is a mismatch between tensorstore and neuroglancer, in that neuroglancer doesn't display a missing chunk the same as a chunk of all zeros?  It might make more sense to fix that issue in Neuroglancer instead.

**Comment by fcollman** [comment]
indeed I concur, perhaps this is a neuroglancer issue instead.
