### ISSUE TITLE
Flaky segfaults when performing many writes quickly 

### ISSUE THREAD

**Issue by co-kuba** [google/tensorstore#30]
Hi!

I'm using jax with their `jax.experimental.global_device_array.GlobalDeviceArray`s and the [serialisation code](https://github.com/google/jax/blob/main/jax/experimental/gda_serialization/serialization.py#L83) they come with, that uses tensorstore.

My use case (checkpointing big neural nets) requires serialising big (many leaves, big array leaves) pytrees of GDAs on large TPU VMs (many workers writing simultaneously).

The setup seems to be stable at a small scale but starts failing nondeterministically when we scale up our models and number of workers. The error we get looks as follows.

```
tensorstore/internal/oauth2/google_auth_provider.cc:173: Using credentials at xxx/.config/gcloud/application_default_credentials.json
tensorstore/internal/oauth2/google_auth_provider.cc:180: Using OAuth2 AuthProvider
*** SIGSEGV received at time=1644534310 on cpu 158 ***
PC: @     0x7fbefa8effd3  (unknown)  tcmalloc::ThreadCache::ReleaseToCentralCache()
    @     0x7fbefa8b23c0  (unknown)  (unknown)
    @                0x5  (unknown)  (unknown)
    @               0xef  (unknown)  (unknown)
    @               0xef  (unknown)  (unknown)
[2022-02-10 23:05:10,337 E 327783 330515] logging.cc:317: *** SIGSEGV received at time=1644534310 on cpu 158 ***
[2022-02-10 23:05:10,337 E 327783 330515] logging.cc:317: PC: @     0x7fbefa8effd3  (unknown)  tcmalloc::ThreadCache::ReleaseToCentralCache()
[2022-02-10 23:05:10,340 E 327783 330515] logging.cc:317:     @     0x7fbefa8b23c0  (unknown)  (unknown)
[2022-02-10 23:05:10,342 E 327783 330515] logging.cc:317:     @                0x5  (unknown)  (unknown)
[2022-02-10 23:05:10,347 E 327783 330515] logging.cc:317:     @               0xef  (unknown)  (unknown)
[2022-02-10 23:05:10,352 E 327783 330515] logging.cc:317:     @               0xef  (unknown)  (unknown)
Fatal Python error: Segmentation fault
```

Anecdotally, it seems that if the first checkpoint gets written ok, the following ones in the same training session also work. Perhaps that is an interesting hint. (I can't swear by it being an absolute rule for now.) The first save fails >50% (but <100%) of the time for one of our common use cases.

---

I'm aware this isn't much info. Don't hesitate to let me know how we could help you understand the problem better. Thank you!

**Comment by jbms** [comment]
If you can provide source code that reproduces the problem that would help a lot in debugging the issue.

If the issue is in fact related to checkpointing then most of the details of your model should not matter --- just the shapes of each parameter and how they are partitioned, so perhaps you could produce a simplified training script that just creates the variables and attempts to checkpoint them, but excludes all of the actual training logic.

**Comment by co-kuba** [comment]
I will work on a minimal reproduction; is there any other stack traces etc that could be useful in the meanwhile?

**Comment by jbms** [comment]
I think it makes sense to just wait until you have a minimal reproduction.

A stack trace would definitely be useful, but to get a useful one you would need a version of the tensorstore library with debugging symbols included, which we currently don't produce --- I think a small tweak to our build configuration would be needed to produce that.  I also suspect that it will be challenging to identify the problem solely from a stack trace anyway.

If for some reason it is problematic to produce a minimal reproduction then it would make sense to explore getting the stack trace.

**Comment by co-kuba** [comment]
Thanks Jeremy, we will get back to this thread as soon as we've had a chance to write a repro we can share!

**Comment by jbms** [comment]
I just wanted to follow up to see if you had been able to resolve or reproduce this issue.

**Comment by co-kuba** [comment]
Thank you Jeremy,
Our team hasn't recently had the bandwidth to work on a reproduction, but we hope to be able to get to it soon! Will keep you updated.
Kuba

**Comment by jiasenlu** [comment]
I met similar issues and seems tensorstore with 0.1.14 can read the checkpoint without any issues. The problem might be introduced after that.

**Comment by jbms** [comment]
I have identified the cause of this and we will have a fix pushed out in the next day or so.
