### ISSUE TITLE
New zlib version zlib-1.2.12 breaks build 

### ISSUE THREAD

**Issue by blasscoc** [google/tensorstore#32]
On March 27 2022, a new version of zlib was released on zlib.net
zlib-1.2.12.tar.gz

This caused the tensorstore build to fail because the url: https://zlib.net/zlib-1.2.11.tar.gz doesn't exist, 
it will say "File Not Found".

Suggested fix:

1. Update the zlib url in tensorstore/third_party/net_zlib/workspace.bzl:

"https://zlib.net/zlib-1.2.11.tar.gz" -> "https://zlib.net/zlib-1.2.12.tar.gz"
replace sha with 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9

This will build zlib but create a conflict compiling png because the ZLIB_VERNUM won't match the one being used to
compile libpng, so bump that version too. 

2. In tensorstore/third_party/png/png.BUILD.bazel:

replace:
PNG_IN_SUBSTITUTIONS = {
    "PNG_ZLIB_VERNUM 0": "PNG_ZLIB_VERNUM 0x12b0",
}

with:
PNG_IN_SUBSTITUTIONS = {
    "PNG_ZLIB_VERNUM 0": "PNG_ZLIB_VERNUM 0x12c0",
}

These changes got the library compiled.

**Comment by jbms** [comment]
Thanks.  That is exactly right.  We actually already had this fix, which is now pushed here: f1256a200d696ac5e7af6766df1b54cc3ad7bf68
