### ISSUE TITLE
setup.py doesn't mandate `numpy` and `wheel` pkgs

### ISSUE THREAD

**Issue by 2bndy5** [google/tensorstore#34]
I just thought I'd open this as feedback to my first experience in following the [install from src instructions](https://google.github.io/tensorstore/installation.html#installation-from-local-checkout).

For the record, I was using `python setup.py develop` from a fresh venv (on windows). I've been trying to keep my global site-packages rather clean lately.

On first try, it failed due to not having `wheel` installed. On second try it failed due to not having `numpy` installed. On third try, it seems to be doing fine, although it's going on 45+ minutes
>[2,568 / 2,572] Compiling src/x86/itx_init_tmpl.c; 2878s local

Although it might be obvious (given the nature of the software), I noticed the `numpy` and `wheel` pkgs are not listed as part of the [build dependencies](https://google.github.io/tensorstore/installation.html#build-dependencies).

**Comment by jbms** [comment]
Thanks for the feedback.  I'll have to update the installation instructions.

The build may be slow in part due to including a number of third party image libraries in order to support various formats.  We may want to provide options to disable that functionality.

**Comment by laramiel** [comment]
The installation instructions include numpy; closing.
