### ISSUE TITLE
mixing sharded and unsharded scales in 'info'

### ISSUE THREAD

**Issue by stephenplaza** [google/tensorstore#4]
thanks for making this package available!

I am attempting to write a volume in neuroglancer sharded format using the spec at the bottom of the email.  When writing is finished, I see a directory for 32x32x32, 16x16x16, and 8x8x8 but not 64x64x64 and 128x128x128 (the two unsharded scales).  Rather it stores these files flat in the directory with info which will lead to collisions.  The neuroglancer web app correctly looks for files in 64x64x64 and 128x128x128.

Here is my info file, thanks for any help!

{"@type": "neuroglancer_multiscale_volume", "data_type": "uint8", "num_channels": 1, "scales": [{"chunk_sizes": [[64, 64, 64]], "encoding": "jpeg", "key": "8.0x8.0x8.0", "resolution": [8, 8, 8], "sharding": {"@type": "neuroglancer_uint64_sharded_v1", "hash": "identity", "minishard_bits": 3, "minishard_index_encoding": "gzip", "preshift_bits": 9, "shard_bits": 18}, "size": [16384, 16384, 1024], "realsize": [16384, 16384, 1024], "offset": [0, 0, 0], "realoffset": [0, 0, 0]}, {"chunk_sizes": [[64, 64, 64]], "encoding": "jpeg", "key": "16.0x16.0x16.0", "resolution": [16, 16, 16], "sharding": {"@type": "neuroglancer_uint64_sharded_v1", "hash": "identity", "minishard_bits": 0, "minishard_index_encoding": "gzip", "preshift_bits": 9, "shard_bits": 18}, "size": [8192, 8192, 512], "realsize": [8192, 8192, 512], "offset": [0, 0, 0], "realoffset": [0, 0, 0]}, {"chunk_sizes": [[64, 64, 64]], "encoding": "jpeg", "key": "32.0x32.0x32.0", "resolution": [32, 32, 32], "sharding": {"@type": "neuroglancer_uint64_sharded_v1", "hash": "identity", "minishard_bits": 0, "minishard_index_encoding": "gzip", "preshift_bits": 6, "shard_bits": 18}, "size": [4096, 4096, 256], "realsize": [4096, 4096, 256], "offset": [0, 0, 0], "realoffset": [0, 0, 0]}, {"chunk_sizes": [[64, 64, 64]], "encoding": "jpeg", "key": "64.0x64.0x64.0", "resolution": [64, 64, 64], "size": [2048, 2048, 128], "realsize": [2048, 2048, 128], "offset": [0, 0, 0], "realoffset": [0, 0, 0]}, {"chunk_sizes": [[64, 64, 64]], "encoding": "jpeg", "key": "128.0x128.0x128.0", "resolution": [128, 128, 128], "size": [1024, 1024, 64], "realsize": [1024, 1024, 64], "offset": [0, 0, 0], "realoffset": [0, 0, 0]}], "type": "image"}

**Comment by jbms** [comment]
Thanks for catching this bug.  I'll get out a fix soon.

**Comment by stephenplaza** [comment]
thanks!!
