### ISSUE TITLE
Mixed dtypes or align data with a different dtype index

### ISSUE THREAD

**Issue by harpone** [google/tensorstore#42]
Hi! TensorStore seems super amazing, can't wait to try this out!

I have lots of time series data with a pandas DateTime index. It would be nice to be able to store also the index, perhaps in a different TensorStore but aligned with the actual data TensorStore, which is just floats.

Is this currently possible?

**Comment by jbms** [comment]
Currently there is no specific date/time data type in tensorstore, though you could use a numeric data type.

**Comment by harpone** [comment]
Yeah not a problem to use e.g. string dtype, but I was wondering if it's possible to have _both_ dtypes in same store... I guess not, so I think I'll just have separate same length stores for the index and data.

**Comment by jbms** [comment]
Yes, separate stores would be needed, because a given TensorStore always has a single data type.

**Comment by harpone** [comment]
OK thanks, I'll do that!
