### ISSUE TITLE
Is it possible to have NaN as default value instead of 0?

### ISSUE THREAD

**Issue by harpone** [google/tensorstore#52]
This would be useful to be able to spot explicitly where data has not been written...

**Comment by jbms** [comment]
The zarr driver does support a user-specified fill value:

https://google.github.io/tensorstore/driver/zarr/index.html#fill-value

Currently no other TensorStore driver supports a user-specified fill value, as no other format defines a way to represent the fill value.

**Comment by harpone** [comment]
OK well I'll just live with that then. Thanks for the reply!

**Comment by jbms** [comment]
Which driver are you using?
