### ISSUE TITLE
Configure failure with CMake on Windows

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#53]
I am trying to build current version (0702389a7cfc245419b7f19ce41b5f08dfcd231f) using CMake 3.24.1. I run into an error during configure step, using both VS2019 and VS2022.
[configure.log](https://github.com/google/tensorstore/files/9830631/configure.log)
[CMakeError.log](https://github.com/google/tensorstore/files/9830629/CMakeError.log)
[CMakeOutput.log](https://github.com/google/tensorstore/files/9830630/CMakeOutput.log)
The relevant files are attached. The most interesting part seems:
```log
Loading C:/Misc/tensorstore-vs22/_deps/liblzma-src/BUILD.bazel
Loading C:/Misc/tensorstore/utils.bzl

MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking Build System
  Creating directories for 'openssl-populate'
  Building Custom Rule C:/Misc/tensorstore-vs22/_deps/openssl-subbuild/CMakeLists.txt
  Performing download step (download, verify and extract) for 'openssl-populate'
  -- Downloading...
     dst='C:/Misc/tensorstore-vs22/_deps/openssl-subbuild/openssl-populate-prefix/src/098695591f3a2665fccef83a3732ecfc99acdcdd.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/google/boringssl/archive/098695591f3a2665fccef83a3732ecfc99acdcdd.tar.gz'
  -- verifying file...
         file='C:/Misc/tensorstore-vs22/_deps/openssl-subbuild/openssl-populate-prefix/src/098695591f3a2665fccef83a3732ecfc99acdcdd.tar.gz'
  -- Downloading... done
  -- extracting...
       src='C:/Misc/tensorstore-vs22/_deps/openssl-subbuild/openssl-populate-prefix/src/098695591f3a2665fccef83a3732ecfc99acdcdd.tar.gz'
       dst='C:/Misc/tensorstore-vs22/_deps/openssl-src'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  No update step for 'openssl-populate'
  Performing patch step for 'openssl-populate'
  patching file BUILD
  Hunk #1 FAILED at 94 (different line endings).
  1 out of 1 hunk FAILED -- saving rejects to file BUILD.rej
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-mkdir.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-download.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-update.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-patch.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-configure.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-build.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-install.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\0ca2dbcd7bc8bdf4d7847cccd3911000\openssl-populate-test.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\85dde88c802439c23c62ca419e06eb4a\openssl-populate-complete.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeFiles\893e5776bf6d24ff7b85c024db008c0d\openssl-populate.rule;C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\CMakeLists.txt' exited with code 1. [C:\Misc\tensorstore-vs22\_deps\openssl-subbuild\openssl-populate.vcxproj]

CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1601 (message):
  Build step for openssl failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1741:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1741 (cmake_language)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1955 (FetchContent_Populate)
  C:/Misc/tensorstore-vs22/third_party/CMakeLists.txt:3 (FetchContent_MakeAvailable)


Configuring incomplete, errors occurred!
See also "C:/Misc/tensorstore-vs22/CMakeFiles/CMakeOutput.log".
See also "C:/Misc/tensorstore-vs22/CMakeFiles/CMakeError.log".
```
As configure step is successful on Ubuntu 22.04, I assume this error is due to lack of testing on Windows (`Hunk #1 FAILED at 94 (different line endings).`)?

**Comment by dzenanz** [comment]
A repo checked out with `core.autocrlf=false` configures properly.

**Comment by jbms** [comment]
It looks like there may be an issue with our logic for detecting that the CPU type is x86_64; possibly it is related to a difference between the Visual Studio generator and the Ninja generator, which is what we test with, or maybe some other difference between our test environment and your environment.

Can you provide me a dump of all of the cmake variables, and/or the bazel_workspace_info.pickle file from your build directory?

**Comment by jbms** [comment]
Actually the cmake variables would be more easily obtained from the `bazel_to_cmake_vars.json` file in the build directory.

**Comment by dzenanz** [comment]
[tensorstore-vs19.zip](https://github.com/google/tensorstore/files/9832887/tensorstore-vs19.zip)
This zip contains both files.

**Comment by jbms** [comment]
Thanks.  It looks like the issue was not with the cpu type detection as I initially guessed.  I'm trying now to see if I can reproduce the error myself using the visual studio generator.

**Comment by jbms** [comment]
I am able to reproduce the error locally with the visual studio generator; hopefully I will be able to quickly get to the bottom of it.

**Comment by jbms** [comment]
The issue appears to be related to an underscore prefix being added to the external symbols defined in the .asm files compiled using nasm --- the missing symbols are present in JPEG_simd_x86_64_asm.lib with an underscore prefix.  I still need to figure out why this is occurring only with the Visual Studio generator, though.

**Comment by jbms** [comment]
It appears that the Visual Studio generator is adding /DWIN32 to the nasm command --- you can see that it ends up in `_deps/jpeg-build/JPEG_simd_x86_64_asm.vcxproj` under PreprocessorDefinitions.

This confuses the logic used in libjpeg-turbo to determine whether to add an underscore to the exported symbols.  It expects that WIN64 will be defined but WIN32 will not be defined, when building for 64-bit windows.

It looks like the libjpeg-turbo project avoids this problem by using a custom command rather than the built-in nasm language support when using the visual studio generator:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/eb0a024af2d84467b22484a89e98e25b3c38025a/simd/CMakeLists.txt#L180

**Comment by jbms** [comment]
Please let me know if you run into any further issues.

It now builds successfully for me with `CMAKE_GENERATOR="Visual Studio 16 2019", and the `core.autocrlf` mitigation is no longer needed either.

However, given that the Visual Studio generator is much slower both at configure time and build time, and does not support sccache, I would still recommend using the Ninja generator instead for a significantly improved development experience (and that applies not just to this project, but to cmake generally)

**Comment by dzenanz** [comment]
Thanks for fixing this quickly.
