### ISSUE TITLE
pickling tensorstore.TensorStore

### ISSUE THREAD

**Issue by d-v-b** [google/tensorstore#6]
It appears that `TensorStore` objects cannot be pickled, at least by cloudpickle or the python standard library's pickle. This is a blocker for distributed computing with tensorstore arrays, e.g. via dask. What would need to change in order to get this resolved?

**Comment by jbms** [comment]
You could get most of the way there by calling .spec().to_json() to convert to JSON, and then pickling the JSON, and then to unpickle, first unpickle the JSON then call tensorstore.open(json).result()

You could implement this separate from TensorStore, but this simple form of pickling could also be added to TensorStore quite easily.

The thing that would be missing from this form of pickling is that all of the unpickled TensorStore objects would use independent Context objects, so they wouldn't share caches at all.  To fix that would require a special pickling implementation for Context, but can still be done.

I will look into implementing this.

**Comment by d-v-b** [comment]
the main appeal of pickling the tensorstore object directly (rather than pickling the spec, i.e. the "ingredients") is that it would play very nicely with [dask.array.store](https://docs.dask.org/en/latest/array-api.html#dask.array.store), which tries to stuff distributed array chunks into a storage object that presents with an array-like interface. But it's not terrible to serialize the json and reconstitute the tensorstore on my worker machines.

**Comment by jbms** [comment]
As an update, I have an implementation of pickling that is close to ready (with correct handling of Context) and I hope to push it out later today.

**Comment by jbms** [comment]
Pickling should work now.
