### ISSUE TITLE
Distributed writing from multiple Kubeflow pods

### ISSUE THREAD

**Issue by kyoungrok0517** [google/tensorstore#67]
Hi. I just encountered this library and it seems promising. I have to save chunks of numpy arrays generated from multiple Kubeflow pods. I wonder if such scenario is supported out-of-the-box or require some synchronization handling. Thanks!

**Comment by jbms** [comment]
It will work out of the box with no extra synchronization if writing to gcs or a distributed filesystem that supports the normal Unix filesystem lock apis.

Performance will be much better if you choose a chunk shape such that each chunk is written by only one process.

**Comment by kyoungrok0517** [comment]
Good to hear that. Thanks!
