### ISSUE TITLE
distributed writes

### ISSUE THREAD

**Issue by d-v-b** [google/tensorstore#7]
I'm trying to write a tensorstore array using dask on a single machine. I have a bunch of worker processes that each a) call `tensorstore.open(spec, write=True).result()`, and then attempt to assign a numpy array to a contiguous, chunk-aligned range of indices in the resulting tensorstore array. This does not appear to be running in parallel. 

How can I make this work? Are there any best practices for writing to tensorstore arrays from multiple processes that I should be aware of?

**Comment by jbms** [comment]
This should work.  Can you send a simple example that demonstrates the problem so that I can look into it?

**Comment by d-v-b** [comment]
I made a minimal reproducible example which confirms what you say -- multiprocess writes work fine. So I must be doing something wrong in the code that wasn't parallelizing properly.
