### ISSUE TITLE
Adding extra metadata/info to `attributes.json` config?

### ISSUE THREAD

**Issue by harpone** [google/tensorstore#73]
So I have the standard config stuff,

```
config_write = {
            "driver": "n5",
            'kvstore': kvstore,
            "metadata": {
                "dimensions": dimensions,
                "blockSize": block_size,
                "dataType": "float32",
                "compression": {"type": "blosc", "cname": "blosclz", "clevel": 5, "shuffle": 2}
            },
            'create': True,
            'delete_existing': True,
            'context': {
                'cache_pool': {
                    'total_bytes_limit': 100_000_000
                }
            }
        }
```

and I was thinking it would be useful to be able to add my own informative metadata into the config, like

`config_write['datetime_start'] = str(index_dt[0])` etc.

But I'm getting `ValueError: Object includes extra members...`.

Is it possible to include this kind of info in the attributes or should I just use a separate json etc?

**Comment by jbms** [comment]
With n5 you can in fact add extra members to the `metadata` field, and they will be included in the `attributes.json` file.

However, a proper interface for user-defined attributes is still on the TODO list.
