### ISSUE TITLE
Error writing to .zarray when trying to write some *new* data in an existing tensorstore

### ISSUE THREAD

**Issue by harpone** [google/tensorstore#75]
I created a zarr tensorstore in GCS and when I'm trying to add some new data I get the error

`ValueError: Error opening "zarr" driver: Error writing gs://bucketname/data/.zarray`

Here's the config:

```
# Def GCS storage:
  kvstore = {'driver': 'gcs', 'bucket': 'bucketname', 'path': f'{ts_folder}/data'}

  config_write = {
      "driver": "zarr",
      'kvstore': kvstore,
      "metadata": {
          "shape": dimensions,
          "chunks": block_size,
          "dtype": "<f4",  # float32
          "compressor": {"id": "blosc", "clevel": 5, "cname": "lz4"},
          "fill_value": "NaN"
      },
      'create': True,
      'delete_existing': False,
      'context': {
          'cache_pool': {
              'total_bytes_limit': 100_000_000
          }
      }
  }
```

the `dimensions` or other parameters do not change when I'm trying to write the new data, so I don't really understand why `.zarray` would need to be rewritten... 

I'd greatly appreciate if anyone can spot what's going on here!

**Comment by jbms** [comment]
You need to specify:

```python
{..., 'create': True, 'open': True}
```

to allow either open or create.

**Comment by harpone** [comment]
Ah, of course! Working now, thanks!
