### ISSUE TITLE
Ability to set log levels?

### ISSUE THREAD

**Issue by lsgos** [google/tensorstore#76]
Tensorstore is quite verbose; for instance, it prints a logging message about using the default admission_queue and which service account it runs on when running on GCE. It would be nice to be able to filter these out, but as far as I can tell they are written directly to standard out (https://github.com/google/tensorstore/blob/master/tensorstore/internal/log_message.cc#L23) with no option to configure the logging level, even by setting an environment variable or similar. In our application, which uses tensorstore to save checkpoints across a distributed application with many workers, these messages are written into our logs n_workers times every single run, which causes a significant amount of noise.

**Comment by laramiel** [comment]
I am working on replacing our logging with the recently released [Abseil logging](https://abseil.io/docs/cpp/guides/logging
). The Abseil library includes a notion of log levels and the ability to select the minimal log levels to output to stderr via flags or global configuration. Most of our logging will translate to an Abseil INFO level, and the default output level is set to ERROR, which should silence nearly all logging once submitted.

https://github.com/abseil/abseil-cpp/blob/master/absl/log/flags.h
https://github.com/abseil/abseil-cpp/blob/master/absl/log/globals.h

**Comment by laramiel** [comment]
Verbose logging is supported as of  https://github.com/google/tensorstore/commit/00b4519ac8ebcc6f46e2bfaa4f4a3edc2b8faee1
