### ISSUE TITLE
zarr fill_value 0.0 for uint8 data type

### ISSUE THREAD

**Issue by toloudis** [google/tensorstore#79]
I am trying to load Zarr via tensorstore (C++ api).
The zarr at this location: 
https://s3.embl.de/i2k-2020/platy-raw.ome.zarr/
Is failing due to:

...\build\_deps\tensorstore-src\tensorstore/util/result.h:417: Status not ok: status(): FAILED_PRECONDITION: Error opening "zarr" driver: Error reading https://s3.embl.de/i2k-2020/platy-raw.ome.zarr/s0/.zarray: Error parsing object member "fill_value": Expected integer in the range [0, 255], but received: 0.0 [tensorstore_spec='{\"context\":{\"cache_pool\":{},\"data_copy_concurrency\":{},\"http_request_concurrency\":{},\"http_request_retries\":{}},\"driver\":\"zarr\",\"kvstore\":{\"base_url\":\"https://s3.embl.de\",\"driver\":\"http\",\"path\":\"/i2k-2020/platy-raw.ome.zarr/s0/\"}}']

This has occurred in tensorstore 0.1.28 and 0.1.31 .Should I consider this bad data or should tensorstore be more forgiving about fill_value=0.0?

**Comment by jbms** [comment]
What tool is generating this data?  Perhaps tensorstore should be more lenient.

**Comment by toloudis** [comment]
Unfortunately I am not involved in the creation of the data but have recently seen it used as an example with other Zarr loaders/viewers.
Example: https://ome.github.io/ome-ngff-validator/?source=https://s3.embl.de/i2k-2020/platy-raw.ome.zarr which uses zarr.js as its underlying loader.  (I know, not fair to compare how js handles numbers vs C++.)
