### ISSUE TITLE
jpeg quality

### ISSUE THREAD

**Issue by d-v-b** [google/tensorstore#8]
How can I adjust the quality setting in jpeg compression? My cursory search through the codebase suggests it might be [hard-coded](https://github.com/google/tensorstore/blob/7ab3603eb2837448c8bb6bf58c7435f024aa605d/tensorstore/internal/compression/jpeg.h#L30) to 75?

**Comment by jbms** [comment]
You are correct that it is currently not configurable.  neuroglancer_precomputed format needs a jpeg_quality option, then it could be passed through and set here: https://github.com/google/tensorstore/blob/7ab3603eb2837448c8bb6bf58c7435f024aa605d/tensorstore/driver/neuroglancer_precomputed/chunk_encoding.cc#L218
