### ISSUE TITLE
Redundant static_pointer_cast overload in C++20 mode

### ISSUE THREAD

**Issue by jbms** [google/tensorstore#80]
It looks like you are building in c++20 mode, which we haven't yet tested, but definitely intend to support.

The issue is this overload here: https://github.com/google/tensorstore/blob/c1f2cebf1d7ffcd54d60200a059cdac723795feb/tensorstore/internal/memory.h#L65

We need to disable that overload when in C++20 mode.

_Originally posted by @jbms in https://github.com/google/tensorstore/issues/36#issuecomment-1427297279_

**Comment by crl123** [comment]
I switched to standard c++-11 and it worked. Thank you very much
