### ISSUE TITLE
Converting c-order array to fortran-order array

### ISSUE THREAD

**Issue by sameeul** [google/tensorstore#87]
Hi, this is more of an API/ Documentation question on the C++ side. Is there a way to create a view/copy of c-order array to fortran-order array? I have a use case, where I am reading c-order zarr files and creating neuroglancer precomputed files. Since, neuroglancer precomputed files are of fortran order, the final image appears rotated by 90 in the neuroglancer viewer. I have the following code that works but I am trying to see if there is a more native way to do this?
```
  auto image_shape = source.domain().shape();
  auto image_width = image_shape[4];
  auto image_height = image_shape[3];
  std::vector<uint16_t> read_buffer(image_width*image_height);
  auto in_array = tensorstore::Array(read_buffer.data(), {image_height,image_width}, tensorstore::c_order);

  tensorstore::Read(source | 
          tensorstore::Dims(3).ClosedInterval(0, image_height-1) |
          tensorstore::Dims(4).ClosedInterval(0, image_width-1) ,
          tensorstore::UnownedToShared(in_array)).value();

  auto out_array = tensorstore::Array(read_buffer.data(), {image_width,image_height}, tensorstore::fortran_order);
  tensorstore::Write(UnownedToShared(out_array),  dest | 
                                    tensorstore::Dims(2, 3).IndexSlice({0,0})|
                                    tensorstore::Dims(1).ClosedInterval(y_loc, y_loc+image_height-1) | 
                                    tensorstore::Dims(0).ClosedInterval(x_loc, x_loc+image_width-1)).value();
```
I am trying to see, if there is a way to just allocate an array using the following code and then later get a copy/view of the array with fortran order.
```
auto array = tensorstore::AllocateArray({image_height, image_width},tensorstore::c_order,
                                                      tensorstore::value_init, source.dtype());
```
 Now that I have `array`, what is the easy way to convert it to a fortran order array?

I have couple of issue with the approach that I mentioned above. First, I don't know the `source` data type upfront and cannot deduce `read_buffer`'s type runtime. Also, instead of calling `value()` on the `tensorstore::Wrtie` operation immediately, if I decide to let it run in a background thread, there is a constrain with the scope of `read_buffer` in my current design. so, if I can get a native tensorstore API to handle that, it would be great for me.

**Comment by jbms** [comment]
You can do:

```c++
tensorstore::Write(in_array, dest | tensorstore::Dims(2, 3).IndexSlice(0) | tensorstore::Dims(1).SizedInterval(y_loc, image_height) | tensorstore::Dims(0).SizedInterval(x_loc, image_width) | tensorstore::Dims(0, 1).Transpose({1, 0})).value()
```
