### ISSUE TITLE
Reading data from neuroglancer in the correct order

### ISSUE THREAD

**Issue by LarsKoeppel** [google/tensorstore#90]
I tried to read an image from neuroglancer. For this I used the following code.

```
std::vector<T> buffer(numberOfPixelsD1 * numberOfPixelsD2 * numberOfPixelsD3 * numberOfPixelsD4);  
auto arr = tensorstore::Array(buffer.data(), {numberOfPixelsD1, numberOfPixelsD2, numberOfPixelsD3, numberOfPixelsD4}, tensorstore::column_major_order);  
tensorstore::Read(store | intervalD1 | intervalD2 | intervalD3, tensorstore::UnownedToShared(arr)).value();
```

For this I had to try out, with which order the picture is displayed correctly. So `c_order`, `row_major_order` or `column_major_order`.

Is there a way to read this information from the neuroglancer data or do you always have to look at the result?

**Comment by jbms** [comment]
There is both the logical dimension order and the physical memory layout of an in-memory array.  These are independent in tensorstore.

It sounds like you want x to be contiguous in memory, i.e. xyzc Fortran/column-major order, or equivalently, czyx c-order/row-major.

The neuroglancer_precomputed driver has the dimension order x, y, z, channel by default.

Therefore you can either read it directly to a Fortran order array (as in your snippet) or transpose it, e.g. with `Dims("channel","z","y","x").Transpose()` and then read it to a c-order array.

**Comment by jbms** [comment]
> OK. Thank you very much for this information.
> 
> Is there a difference in efficiency between my variant and using `Transpose()`?

No.
