### ISSUE TITLE
Any plans to implement ZEP0002 - Sharding codec?

### ISSUE THREAD

**Issue by JackKelly** [google/tensorstore#97]
I'm really excited about `tensorstore` - thank you for all your hard work!

I was just curious if you have any plans to implement [Zarr Enhancement Proposal (ZEP) 0002 - Sharding codec](https://zarr.dev/zeps/draft/ZEP0002.html)?

**Comment by jbms** [comment]
Yes, we are planning to implement zarr v3 and sharding very soon.

**Comment by JackKelly** [comment]
Awesome, thank you!

**Comment by tasansal** [comment]
Super awesome to hear v3 support coming soon! Thanks for all the hard work @jbms

**Comment by jbms** [comment]
Zarr v3 with sharding is now supported.
